### ISSUE TITLE
[feature-request] Please create both Bitcoin and Bitcoin Cash wallets at first-run wizard

### ISSUE THREAD

**Issue by Technologov** [Bitcoin-com/Wallet#10]
Bitcoin-com-wallet-3.6.0-win64 on Windows 7 x64. (Chrome v60)

Default wallet create is "Bitcoin", while I recommend to create BOTH Bitcoin and Bitcoin Cash wallets. (with different address spaces, to reduce user confusion)

-Technologov

**Comment by magmahindenburg** [comment]
We plan to add this in the next release.

**Comment by jepps32** [comment]
I hope we are. Going to make. Some bitcoins
