### ISSUE TITLE
Make BCC default when sending Bitcoin Cash

### ISSUE THREAD

**Issue by abrkn** [Bitcoin-com/Wallet#12]
System: Android
Version: v3.6.0
Commit hash: #13d9127

The current default is "Legacy", which I assume means "Not Segwit".

![legacy](https://user-images.githubusercontent.com/843958/30011790-22963868-916d-11e7-92bf-916fba8b436c.png)

**Comment by Bitcoin-Ornn** [comment]
Hey abrkn,

This issue has been resolved, I appreciate the report.

Regards,
Ornn.
