### ISSUE TITLE
No Mac Version Built For Latest Release?

### ISSUE THREAD

**Issue by KeyJockey** [Bitcoin-com/Wallet#150]
Hey guys... my copy of the bitcoin.com wallet on MacBook, OSX, is prompting for a new version 4.10.1 but the link has only Linux and Windows downloads...
![macmissing](https://user-images.githubusercontent.com/13903392/40630207-a5838016-629e-11e8-8b55-97261aad92e6.png)

...BUT there is nothing (yet?) for MAC and it's been a couple days already.

IF there's not gonna be a Mac build for some releases, there needs to be a "skip" or "dismiss" button on the upgrade notice, as it's otherwise really annoying to have to see it there huge at the top of the window and no way to get rid of it.

![notice](https://user-images.githubusercontent.com/13903392/40559596-4b7a447c-6025-11e8-8c06-1f4dd99d780b.png)

**Comment by drshields** [comment]
Having the same issue here. Agree with @KeyJockey suggestion to skip / dismiss if there is not actually a new version available.

**Comment by David-R-Allen** [comment]
And I too am having the same issue. I hope this was an oversight and there is a new version for the MAC. Upgrades should be across the board for all OS.

**Comment by alfonsofy** [comment]
Hello everybody,

We have added the .dmg files for the last release and will continue to do so.

Also, we included the Bitcoin.com Wallet in the Mac App Store where you will be able to receive automatic updates.

Thank you for reporting.

**Comment by brendoncoin** [comment]
It's now been updated.

**Comment by lonestar1234** [comment]
Hi @KeyJockey, Synapsi.com admin here. Sorry for writing you here, but it seems rather difficult to reach you anywhere else. It looks like you once used our service, and even though we shut it down, we've recently been going through our Database backup and found out you still have some funds locked in escrow for the question "Manual Override Dynamic Fee in Copay wallet".

Would you be interested in getting them back? Please check your @yahoo email and respond or reply back here on Github or on bitcointalk.org.
