### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by jcramer** [Bitcoin-com/Wallet#157]
Hi, when setting up a multi-sig wallet on my phone I noticed a minor typo in one of the error messages.  Looks like this occurs in many files.

<img width="500" alt="screen shot 2018-05-31 at 2 05 01 pm" src="https://user-images.githubusercontent.com/988195/40799508-c05f3756-64db-11e8-8bdf-4d67fbbe3cf5.png">

**Comment by Bitkilo** [comment]
Thank you for reporting this to us. We should have this fixed for the next release
