### ISSUE TITLE
Wallet for Apple iPad : vertical only

### ISSUE THREAD

**Issue by Technologov** [Bitcoin-com/Wallet#16]
For some reason, the Bitcoin.com App for Apple iPad always forces me to vertical layout, while I typically work in horizontal mode, like on a Laptop. 

Apple IOS v11 BETA on iPad Pro 10.5 + Bitcoin.com wallet v3.6.0

**Comment by Bitcoin-Ornn** [comment]
Hey Technologov,

We have had some extensive overhauls since this issue was created, we are currently on Version 4.8.

If you are still having this issue do let me know, but I believe it may have been addressed in one of the recent updates.

Regards,
Ornn.
