### ISSUE TITLE
Remove "Send max amount" from "Request Specific Amount"

### ISSUE THREAD

**Issue by manufoy** [Bitcoin-com/Wallet#169]
Under "Request Specific Amount" there's a button which says  "Send max amount", this button is leftover from the send option, and completely irrelevant to requesting an amount. 
<img width="400" alt="screen shot 2018-06-09 at 11 14 57 pm" src="https://user-images.githubusercontent.com/9674850/41193127-e4bda9fa-6c3a-11e8-862b-f77dd51053f9.png">
<img width="400" alt="screen shot 2018-06-09 at 11 15 02 pm" src="https://user-images.githubusercontent.com/9674850/41193128-e5462b18-6c3a-11e8-9d40-4b5c2d0b2b41.png">

**Comment by Nathapon8899** [comment]
#169

**Comment by manufoy** [comment]
https://github.com/Bitcoin-com/Wallet/pull/298

**Comment by manufoy** [comment]
Issue is fixed in latest release.
