### ISSUE TITLE
the 12 keywords cannot import into bitpay wallet app!!!

### ISSUE THREAD

**Issue by daffy6537** [Bitcoin-com/Wallet#173]
I wonder if bitcoin.com wallet someday in future years won't service us any more, how can we get back our wallet and coin?

**Comment by mpatc** [comment]
AFAIK, this app is using bip 39. I don't know about bitpay, but have you tried using the 12 words into another app that is bip 39 compliant? Here is one https://iancoleman.io/bip39/

To answer your question, you can read up on how bip 39 works [here](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki). That explains how to derive wallet address and keys from you 12 words. This way, even if this app, and bitpay and every other wallet in the world stops working, you can still easily derive your keys.

**Comment by zowki** [comment]
This wallet uses BIP39 words, which can be imported into other wallets such as Bitpay, Electrum, Electron Cash etc. Closing this issue.
