### ISSUE TITLE
Backup phrase 12 words not valid

### ISSUE THREAD

**Issue by ishij** [Bitcoin-com/Wallet#190]
Forgot spending password, followed the specified steps to recover , diwnloaded the wallet on other device, import wallet , entered the correct 12 words, unable to import wallet

Thaks4 in Advance

**Comment by zowki** [comment]
Please check that the 12 words are spelled correctly.

Full list of words here:
https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by Bitkilo** [comment]
What error message do you receive from the wallet?
