### ISSUE TITLE
Error sweeping wallet: BADREQUEST: Invalid coin

### ISSUE THREAD

**Issue by bitcoindevotee** [Bitcoin-com/Wallet#199]
Hi, Sweeping BCH from a paper wallet does not work. 
I am using Android and Bitcoin.com wallet 4.11-hotfix1
It works fine in the original CoPay App v4.4.0.
The sweep finds both the BTC and the BCH, sweeping BTC works fine, but when sweeping BCH the following error message appears: Error sweeping wallet: BADREQUEST: Invalid coin

**Comment by Bitkilo** [comment]
Hello, 
I use the Bitcoin.com wallet, and sweep paper wallets about once a week. In the whole time i have been using this wallet, i have only seen this error once and that was also with BCH (after scanning the private key a couple more times it worked)
This should not happen anymore.

Please update to the latest version of the wallet - v4.12.2
You can update your wallet from the play store, or directly from this link: https://wallet.bitcoin.com/
