### ISSUE TITLE
Price chart is displayed in USD

### ISSUE THREAD

**Issue by econnok** [Bitcoin-com/Wallet#2]
Not sure if this is something you want, but the price chart currently displays in USD instead of the selected 'Alternative Currency'. The type of currency the price chart is referring to is not identifed, so may be confusing to some.

**Comment by akihiro1** [comment]
0.5

**Comment by Bitcoin-Ornn** [comment]
Hey Econnok,

I am currently filtering through these Github issues and after reviewing the Bitcoin.com Wallet, this should have been addressed. I've confirmed it is working on the latest release which is V4,8.

I appreciate the report and I apologize for the lack of communication.

Regards,
Ornn.
