### ISSUE TITLE
[iOS] Unable to import Wallet

### ISSUE THREAD

**Issue by binarykitchen** [Bitcoin-com/Wallet#22]
With your latest iOS app I am unable to import a Wallet under the File/Text tab. When long-pressing and selecting the paste option, nothing happens.

I have copied the contents of my private Wallet (64kB large) in another app and fail to paste here.

Known bug?

**Comment by Bitcoin-Ornn** [comment]
Hey binarykitchen,

The Bitcoin.com Wallet has changed significantly since you created this issue, we are currently on V4.8.0 - If you can test this again for me I would really appreciate it. 

If this is still an issue please do reach out,

Regards,
Ornn.

**Comment by binarykitchen** [comment]
nope, still can't paste plain text code to import wallet. upon paste nothing happens, no error, no text, just nothing.

**Comment by Bitcoin-Ornn** [comment]
Reporting this to the development team binarykitchen, if I need further information I'll reach out.
