### ISSUE TITLE
Lost Backup Key, Unable to open wallet

### ISSUE THREAD

**Issue by smokenmirrors2** [Bitcoin-com/Wallet#225]
I was using the bitcoin.com wallet on my pc, I had the files stored on an external hdd, thinking that the wallet itself, and keys, was stored within the program files. I have now came to the conclusion that I was wrong because I reinstalled windows and now when I open the wallet, I am now being asked to create a new one. Where does this program store files that it uses to access the wallet that is created??????????????

**Comment by Bitkilo** [comment]
Hello, 

I would like to help you with this.
Could you please email wallet@bitcoin.com and ask for the ticket to be assigned to "Steven"
It will be much easier to deal with this via our support system.

When you email support, please let me know if you "exported" your Bitcoin.com wallet files to your external HD, and if so did also export your wallet private keys?

I will keep an eye out for your email.

Regards:
Steven.
