### ISSUE TITLE
BitPay

### ISSUE THREAD

**Issue by xAsrielDreemurr** [Bitcoin-com/Wallet#24]
Cannot Import bitcoin.com wallet into bitpay.  can anyone help me?

**Comment by teran-mckinney** [comment]
You can change the Bitcore Wallet Server from ....bitcoin... to ...bitpay...

That partly worked for me but had some issues. Just ransfering coins from one into the othe may be easiest, but hopefully someone with some actual Copay/BWS experience can chime in.

**Comment by Bitcoin-Ornn** [comment]
Hey xAsrielDreemurr,

I believe these issues have been resolved in the recent releases as such I will be closing this issue, if you still are having problems do reach out.

Regards,
Ornn.
