### ISSUE TITLE
Change all references from BCC to BCH

### ISSUE THREAD

**Issue by Bergerton** [Bitcoin-com/Wallet#25]
Hello,

I was recently on a reddit thread where Roger Ver [claimed all references to BCC in the wallet app are outdated and it was corrected to BCH in a later versions](https://www.reddit.com/r/btc/comments/7ddzmr/i_just_started_paying_for_this_bitcoin_cash_radio/dpx0o61/
).  As you'll notice in my comments immediately below, i'm still seeing BCC all over the place.

I'm offering my time to take a swing at putting together a pull request if you want/need the help.
If it's easier for somebody else who's already in the swing of things to run the find/replace, that's cool too; just lemme know.

Thanks!

**Comment by Bitcoin-Ornn** [comment]
Hey Bergerton,

I have been reviewing the latest version of the Wallet and I believe these have all been addressed, however, if you notice them pop up on the latest version do let me know and I'll get the team to address them.

Regards,
Darren.
