### ISSUE TITLE
[solved]restore wallet with backup phrase

### ISSUE THREAD

**Issue by hellboyboyhell** [Bitcoin-com/Wallet#3]
hi
i have a problem with restoring my wallet and i sent many emailes to bitcoin.com but didnt recieve any answer
when i want to import my wallet this error happens:
"Could not access the wallet at the server. Please check:
The password of the recovery phrase (if set)
The derivation path
The wallet service URL"

i had restored my wallet once before and no any problem... but this time this error repeated...
what can i do?

**Comment by hellboyboyhell** [comment]
this is bitcoin.com admins[fremont] solution:

Please uninstall the Bitcoin.com wallet then reinstall, create a new wallet and then do the following:

Go "New Personal Wallet" -> Advanced -> Walley Key, Select "Specify Recovery Phrase", then enter the 12 words as recovery phrase. Create the wallet (this will show '0' at first), then click on "Receive" and then "Generate new address" until the address with the balance appears. After that the balance will show properly.

**Comment by jcansdale** [comment]
I'm trying to extract BCH from blockchain.info.

After entering by backup phrase, this tip restored some of my BCH but not all of it.

After hitting `Generate new address` a bunch of times, I get a dialog saying `Empty addresses limit reached. New addresses cannot be generated`.

I wonder if I'm out of luck or if anything can be done?

**Comment by bitcoinstore** [comment]
I would recommend using this tool to recover all your BCC:  https://blog.bitpay.com/bitcoin-cash-recovery/

**Comment by jcansdale** [comment]
@bitcoinstore that did the trick, thanks!

I have another wallet where I have the `Private Key` but no recovery phrase. You wouldn't happen to know a way to do the same with that? 😄

**Comment by magmahindenburg** [comment]
If you have the HD key you can generate all addresses in your wallet, but if you only have one private key you will only be able to sweep that address.

**Comment by bitcoinstore** [comment]
Just use the scanner (middle tab, send tab), or paste the private key in the send tab input and a contextual menu will be shown.  I'll have to test if this works with the BCH version, or only the BTC version

**Comment by jcansdale** [comment]
@bitcoinstore, @magmahindenburg,

> or paste the private key in the send tab input and a contextual menu will be shown.

Ah, this is the bit I was missing. I didn't expect to find it on the send tab, but I guess sweeping is sending coins to one of your own addresses. 👍

Thanks again!
