### ISSUE TITLE
App does not show or update the number of BCH transaction confirmations

### ISSUE THREAD

**Issue by n9jd34x04l151ho4** [Bitcoin-com/Wallet#30]
I sent some funds to my Bitcoin.com wallet. The confirmations are showing up as 3 on the Bitcoin.com block explorer. Also Electron Cash shows up as 3 confirmations (the wallet I sent from). However my Bitcoin.com wallet where the funds are being received to just shows `Receiving` with Confirmations showing as `Unconfirmed`. This does not update after refresh either:

![image](https://user-images.githubusercontent.com/31981309/33809324-3c28eaee-dddc-11e7-907a-1ff56986440c.png)

![image](https://user-images.githubusercontent.com/31981309/33809290-d705d848-dddb-11e7-9b04-518d9b3da4c8.png)

I think this should show the number of confirmations.

**Comment by Bitcoin-Ornn** [comment]
Hey n9jd34x04l151ho4,

Again, sorry for the lack of communication on this issue. This issue has been addressed and I have tested that it working on my device. 

Regards,
Ornn.
