### ISSUE TITLE
https://github.com/samaaron/sonic-pi/commits/master

### ISSUE THREAD

**Issue by pysmith78** [Bitcoin-com/Wallet#300]
I'm completing lost as well when it comes to wallets. Which wallet is "The Wallet".. I have so many. All showing a 0 balance. Can't be right. 0x829BD824B016326A401d083B33D092293333A830

**Comment by FutureMoon** [comment]
so i am

2018년 8월 24일 (금) 오후 6:04, pysmith78 <notifications@github.com>님이 작성:
