### ISSUE TITLE
Bug scanning BCH legacy address format prevents sending payment

### ISSUE THREAD

**Issue by woodser** [Bitcoin-com/Wallet#317]
Steps to reproduce:
1. Wallet contains only BCH, no BTC
2. Scan legacy address format QR code
3. Select "Send payment to this address"
4. Amount input screen displayed.  Number inputs ignored.  No currency displayed.

This bug will prevent a customer from making a payment if the merchant provides a legacy address QR code to scan.

Workaround:
1. Scan legacy QR code
2. Select "Copy to clipboard"
3. Paste in the send tab
4. Screen is presented to select BCH or BTC
5. Amount input screen works as expected

**Comment by theRealBitcoinClub** [comment]
With the newest version this seems to be resolved! Why did nobody comment on that issue? Do the developers care at all about these issues?

**Comment by alfonsofy** [comment]
@theRealBitcoinClub thanks for keeping this thread open.

@woodser this should be fixed. Will close the issue and please get back to us if you see it happening again.
