### ISSUE TITLE
The Scan QR Button is unnecessary on the send screen!

### ISSUE THREAD

**Issue by theRealBitcoinClub** [Bitcoin-com/Wallet#397]
When I go to the "send" page and there is the button "Scan QR Code" which has a green background it is difficult for the user to realize that this is a button! You should always use the same colors for all the action buttons! I see 3 buttons with 3 different background there!

**You should remove that option completely from that screen because it is already in the main menu and it is even on the top buttons!**

Too many buttons on one screen make it hard for the user to understand whats going on!

**Comment by alfonsofy** [comment]
Again, thanks for voicing your concerns, we'll take them into account in future redesigns.
