### ISSUE TITLE
Send Page Layout: It is hard for the user to realize that you have a contacts book!

### ISSUE THREAD

**Issue by theRealBitcoinClub** [Bitcoin-com/Wallet#399]
On the send page you should have 2 buttons and one input field only!

I did not realize that you have any contacts book function until recently when you added the new choose screen after scanning a QR code, because that information was always hidden on the bottom and I simply did not had any reason to swipe down.

1. On the top the input field for the address to paste it

2. In the middle you should have a contacts book button

3. Below that you should have a button to send from one internal wallet to the other

**All the buttons should have the same background and color!**

**All buttons should have one icon and text, not only text like the specific amount button!**

**The Icon should always be on the left side of the text!**

**Comment by alfonsofy** [comment]
Thanks for reporting your concerns. We'll take them into account in a future redesign.
