### ISSUE TITLE
Multisignature support for bitcoin cash

### ISSUE THREAD

**Issue by Quark-Fusion** [Bitcoin-com/Wallet#4]
Creating new wallet and import from backup/seed.

**Comment by Bitcoin-Ornn** [comment]
Hey Quark-Fusion,

First off, I want to apologize for the lack of communication on this, I am currently working through all of our GitHub issues. We have added Multisignature support in one of the Bitcoin.com Wallet releases.

You can find more information here: https://www.bitcoin.com/guides/how-to-create-a-shared-bitcoin-wallet

I appreciate you submitting this issue and if you experience any others, feel free to reach out.

Regards,
Ornn.
