### ISSUE TITLE
Mention disk space required

### ISSUE THREAD

**Issue by jidanni** [Bitcoin-com/Wallet#40]
In README.md this step
```
npm run apply:bitcoincom
```
downloads additional components from the net. Please be sure to mention
there how much disk space will be needed before the user runs the command.
One megabyte? One gigabyte?

Even if the user has a large disk, he might have a slow connection, and
would like to have an idea of how much time it might take.

Also mention further disk space estimates for daily use.

**Comment by Bitcoin-Ornn** [comment]
Hey jidanni,


I have submitted this improvement to the development team, hopefully we will see it implemented in the near future.

Regards,
Ornn.
