### ISSUE TITLE
I just received a payment of 180€ which is not showing up in my wallet

### ISSUE THREAD

**Issue by theRealBitcoinClub** [Bitcoin-com/Wallet#403]
**How can I see my Wallet saldo in the explorer.bitcoin.com???**

Your Android Wallet is messing things up, I have just received a payment of 180€ which is showing as sent on the wallet of the IPhone which was sending the transaction but it does not appear in my transaction list.

It has been about one hour now since we did the transaction and I re-started my device and now i did an App Update of your wallet, can you please tell me how can I access my history on a blockexplorer like explorer.bitcoin.com!??!?

**Comment by alfonsofy** [comment]
This bug has been fixed, no need to update the app. Please let us know if you encounter it again, and thanks for reporting.
