### ISSUE TITLE
Add pgp signatures for apk releases

### ISSUE THREAD

**Issue by rikkuspet** [Bitcoin-com/Wallet#454]
Hi.

Firstly, thanks for providing direct apk downloads for android.

Would it be possible to also include sig files for future releases to allow verification before installing? I noticed this has been done in the past:
https://www.bitcoin.com/bitcoinwalletreleases/bitcoin-com-wallet-4.9.1-android.apk.sig
Recent releases however only have signatures for the other platforms.

Thank you.

**Comment by alfonsofy** [comment]
We will definitely do that. We're happy you've enjoyed the direct APK download. We will provide a signature for future releases and update the latest release to include it.

**Comment by rikkuspet** [comment]
Excellent, thank you!
