### ISSUE TITLE
BIP-70 URIs do not work

### ISSUE THREAD

**Issue by teran-mckinney** [Bitcoin-com/Wallet#48]
No Bitpay invoice works. It just thows an error about Bitpay's new Bitcoin Cash address being the only one supported. Tried this multiple times, should be pretty easy to reproduce.

**Comment by Bitcoin-Ornn** [comment]
Hey teran-mckinney,

I appreciate the report, I believe this issue has been addressed,

If you are still having issues with this, do reach out.

Regards,
Ornn.
