### ISSUE TITLE
The upgrade "link" directs to the Copay project

### ISSUE THREAD

**Issue by mkleehammer** [Bitcoin-com/Wallet#5]
This morning there was a notice that "There is a new version of Bitcoin.com Wallet available", but clicking the Download link took me to https://github.com/bitpay/copay/releases/tag/3.7.3

I assume that was missed during the Copay -> Bitcoin.com fork?

**Comment by magmahindenburg** [comment]
Which version and platform are you using? The link is correct on Linux Desktop.

**Comment by mkleehammer** [comment]
Sorry for the delay.  I'm using macOS and version Version 3.5.6 (3.5.6)

**Comment by CameronNemo** [comment]
Bump. Just saw this issue on 4.04 on Linux desktop. I installed by downloading the tarball, if that makes any difference.

**Comment by Bitcoin-Ornn** [comment]
Hey mkleehammer,

I followed up with our development team and I can confirm this issue has been resolved.

Regards,
Ornn.
