### ISSUE TITLE
Update screen in wallet linked me to the wrong GitHub page

### ISSUE THREAD

**Issue by n9jd34x04l151ho4** [Bitcoin-com/Wallet#50]
This screen appeared in my wallet (on Linux):

![bitpay](https://user-images.githubusercontent.com/31981309/34430097-353065c6-ec48-11e7-8ea0-1d5ea683c2af.png)

Clicking that then took me to this link: 

https://github.com/bitpay/copay/releases/tag/v3.9.1

Which is incorrect. I suspect some old legacy code from when you forked their wallet.

**Comment by Bitcoin-Ornn** [comment]
Hey,

I have confirmed with the development team that this issue has been resolved.

Regards,
Ornn.
