### ISSUE TITLE
My money so you pay thd king 

### ISSUE THREAD

**Issue by jparcus56** [Bitcoin-com/Wallet#521]
Ineed my money

**Comment by jparcus56** [comment]
Were is my josh it ant commen

**Comment by Bitkilo** [comment]
Please do not spam our GitHub page

**Comment by jparcus56** [comment]
Ok what do i have to pay you

**Comment by jparcus56** [comment]
Why do I owe you and were is my bitcoin that I suppose to make

**Comment by jparcus56** [comment]
I will do the right as soon has I get my new deit card I am waiting on it now thanks and have a good morning

**Comment by alfonsofy** [comment]
You've been blocked because of spam. If you need help, please contact wallet@bitcoin.com. Thanks.
