### ISSUE TITLE
IOS Issue with copying tx address to clipboard

### ISSUE THREAD

**Issue by CreativeName4** [Bitcoin-com/Wallet#536]
We were playing with this today and it seems there is an issue related to IOS:

After you send a transaction; go to wallet, copy "to" to clipboard; it shows copied to clipboard, but doesn't actually seem to copy, if I paste it to "notes" on my iphone, there is some sort of HTML that looks far more intense than the simple address i'm attempting to paste.

Im_uname confirms this happens with an android version too, perhaps he can chime in.

**Comment by imaginaryusername** [comment]
The problem I got on Android is simply this https://github.com/Bitcoin-com/Wallet/issues/515#issuecomment-473508737 which seems yet to be fixed.

**Comment by Bitkilo** [comment]
This was a problem with both Android and iOS in previous versions. The good news is that we have now fixed this problem in the latest release v5.7.1

Please report back if you have anymore problems.

**Comment by CreativeName4** [comment]
Thank you! I noticed it copies the address as a hyperlink now instead of plain text not sure if it was like that in the past). This is great. Thanks for the fix!

**Comment by alfonsofy** [comment]
@CreativeName4 hello there, can you specify please how it gets copied as a hyperlink? does it copy the right address format? thanks!

**Comment by CreativeName4** [comment]
I just copied, pasted, and emailed it to myself. I think I was wrong, it appears as though it pasted it as a hyperlink, in reality it when clicking on it, it was prompting to open up on iOS with a wallet app (BRD). I need to figure out why BRD has been given default priority to cashaddress when I have several wallets.
