### ISSUE TITLE
Version listed on bitcoin.com (5.6) is later than the latest release on github (5.4)

### ISSUE THREAD

**Issue by JulianTosh** [Bitcoin-com/Wallet#555]
Why is the bitcoin.com website hosting a wallet with version 5.6 when the github is only listing 5.4 as the current release?

Link on bitcoin.com points to https://wallet.bitcoin.com/binaries/bitcoin.com-wallet-5.6-hotfix2-linux-x64.tar.gz and has the hash 10bfd23a9f2590e7088926be945d41fd0a1fe0c9a4dbdebe8a522ece9ac6bb32

**Comment by monsterbitar** [comment]
I too would like to know this, and in particular I would like to know if there is any more current versions of the bitcore-wallet-client/server libraries that bitcoin forked some time ago.

**Comment by Giszmo** [comment]
Has this been resolved? I just started an attempt to verify the binary on Google Play to match the source code but neither on Google Play nor on bitcoin.com is this GitHub even linked, so I'm not sure I'm on the right track. If I forget to update this, my findings will be found [here](https://walletscrutiny.com/posts/com.bitcoin.mwallet/).

**Comment by JulianTosh** [comment]
Apparently, all the versions are here in the repo, but not tagged. You can see all the released versions as branches. Not what I would expect to see, but it is what it is.

**Comment by Giszmo** [comment]
I'm slightly reluctant to even try that out as branches are usually more than one commit, so which one should I use, especially when reviewing older versions? Anyway, we will revise our verdict from "no source" to "not verifiable" and give it another try when we have time.

**Comment by jchau207** [comment]
Apple has been rejecting our desktop releases due to "use of private api" and developers of the offending library (NW.js) have not addressed the issue: https://github.com/nwjs/nw.js/issues/7015. 

If we publish the release on github, the existing clients automatically gets notified to download a new version from Apple's app store but wouldn't be able due to the rejection.
