### ISSUE TITLE
[BLOCKER] Laptop and Netbook resolution : display problems

### ISSUE THREAD

**Issue by Technologov** [Bitcoin-com/Wallet#6]
Laptop (1366x768) and Netbooks (1024x600) displays have severe issues with this wallet.

Bitcoin-com-wallet-3.6.0-win64 on Windows 7 x64. (Chrome v60)

[BLOCKER] On Netbooks and Laptops , this wallet can't be used, because it doesn't fit into the standard 1024x600 resolution. Many GUI buttons are simply not accessible. Most Netbook users are too illiterate to open a bug report. Boo.
See "Bitcoin.com-600px-vertical-resolution-problem.png".
Even on normal laptop (1366x768) resolution, when I first open the app, it displays GUI elements and buttons wrong.
See "Bitcoin.com -- small vertical resolution.png" and "Bitcoin.com - small vertical resolution - receive button invisible.png"
This is a BLOCKER bug, because I can't switch my wallet mode to "receive". 

You can emulate any resolution on VirtualBox machine, so you don't have to hurt your development environment. NOTE: That I do use 125% fonts, because of low vision problems. See screenshot; "Font-size-increase.png"

![bitcoin com - small vertical resolution - receive button invisible](https://user-images.githubusercontent.com/1480628/29997533-74b1f8ee-901e-11e7-8c6b-56db369e4d93.png)
![bitcoin com -- small vertical resolution](https://user-images.githubusercontent.com/1480628/29997534-74b340aa-901e-11e7-8aa7-1083045d8f46.png)
![bitcoin com-600px-vertical-resolution-problem](https://user-images.githubusercontent.com/1480628/29997535-74b4b66a-901e-11e7-99f2-b50e5faa3f4b.png)
![font-size-increase](https://user-images.githubusercontent.com/1480628/30002390-0151a924-90b1-11e7-8e1a-8c35d57c2a16.png)

-Technologov, 02.09.2017

**Comment by Bitcoin-Ornn** [comment]
Hey Technologov,

I appreciate this report, it has been sent on to the development team for review, 

Regards,
Ornn.
