### ISSUE TITLE
Why not build-in keyboard

### ISSUE THREAD

**Issue by xjflyes** [Bitcoin-com/Wallet#74]
# When I entering amount, I can't even see the textbox.

![b1b686e6-13d1-457b-9133-7c6936d86a35](https://user-images.githubusercontent.com/15177248/38722706-56d67cc4-3f31-11e8-94b1-6db22231d75f.jpeg)

# Copay's design is much easier to use.
![a36e8de9-57b1-4f4b-8df5-eacf071d73b1](https://user-images.githubusercontent.com/15177248/38722821-d1499b44-3f31-11e8-8a0a-eba423e6617c.png)

# Can't scrolldown a contact, and the 'delete' button is not working.
![4a8de79a-192f-4a2d-b8bf-18949eb6e9e3](https://user-images.githubusercontent.com/15177248/38723022-69b6d734-3f32-11e8-83ae-af7f660f06f8.png)
# 

# Why 'request specific amount' has a 'send max amount' button, that makes no  sense. And of course not working.

![0948f86d-dbd3-41ff-b8cc-5d12a6a2d263](https://user-images.githubusercontent.com/15177248/38723817-d8a64fec-3f34-11e8-98d7-edf881e51544.png)

# This 'request specific amount' button is on the top of screen, very difficult to touch. Make it bigger like copay is enough.

![74fb8557-6636-4905-b726-de7704d0c912](https://user-images.githubusercontent.com/15177248/38723670-66c4f310-3f34-11e8-95b2-09674b298b3b.jpeg)

![4e4eda9a-aa92-4992-9e9b-337d8b039eb6](https://user-images.githubusercontent.com/15177248/38723965-6077d38c-3f35-11e8-9e16-a4c6953c181c.png)

**Comment by xjflyes** [comment]
And when sweep BCH from paper wallet, the fee setting is extremely high.

**Comment by Bitkilo** [comment]
Thank you for the feedback.

We will be removing the "Send Max Amount" option on the "request specific amount" screen, as this is not at all needed.
The delete contact option works for me, just need to tap "OK"

We do need to look into why sweeping paper wallets are more expensive than a normal BCH transaction, it should be the same at 1sat/B
I sweep a lot of paper wallets and noticed the fee is often higher. I have reported this and it is being worked on.
