### ISSUE TITLE
Bitcoin.com Android wallet stuck at splash screen at startup

### ISSUE THREAD

**Issue by PrzemekFPL** [Bitcoin-com/Wallet#83]
Android 4.4, Samsung Galaxy, Bitcoin.com wallet hangs at the splash screen with the text "Bitcoin.com Wallet". If I switch to another application and back, it shows only white screen. It didn't work right after installation already, it never went past the startup screen. Clearing application data does not help.

**Comment by Bitcoin-Ornn** [comment]
Hey PrzemekFPL,

I have sent this on to the development team to investigate, if I need further information I'll be sure to reach out. 

As always thanks for your report and I hope we can get this bug fixed for you.

Regards
Ornn.
